import Head from "next/head";
import { Inter } from "@next/font/google";
import StartBar from "components/StartBar/StartBar";
import "xp.css/dist/XP.css";
import WinForm from "components/WinForm/WinForm";
import styles from "../styles/Home.module.css";
import DesktopIcon from "components/DesktopIcon/DesktopIcon";
import mycomputer from "../../assets/mycomputer.png";
import bin from "../../assets/recycling_bin.png";
import pdf from "../../assets/pdf.png";
import github from "../../assets/github.png";
import cmd from "../../assets/cmd.png";
import solitare from "../../assets/solitaire.png";
import linkedin from "../../assets/linkedin.png";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const iconClicked = () => {
    console.log("Icon Clicked!");
  };
  const handleOpenGitHub = () => {
    window.open("https://github.com/firwer", "_blank", "noreferrer");
  };

  const handleOpenLinkedin = () => {
    window.open(
      "https://www.linkedin.com/in/poh-wei-pin-7b9061183/",
      "_blank",
      "noreferrer"
    );
  };
  return (
    <>
      <Head>
        <title>Wei Pin's Personal Website - Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DesktopIcon
          doubleClick={iconClicked}
          title="My Computer"
          img={mycomputer}
        />
        <DesktopIcon
          doubleClick={iconClicked}
          title="Recycling Bin"
          img={bin}
        />
        <DesktopIcon doubleClick={iconClicked} title="My Resume" img={pdf} />
        <DesktopIcon
          doubleClick={iconClicked}
          title="My Hobbies"
          img={solitare}
        />
        <DesktopIcon
          doubleClick={handleOpenGitHub}
          title="My Github"
          img={github}
        />
        <DesktopIcon doubleClick={iconClicked} title="My Work" img={cmd} />
        <DesktopIcon
          doubleClick={handleOpenLinkedin}
          title="My LinkedIn"
          img={linkedin}
        />
        <WinForm title="Welcome!" width="500">
          <h3>How to Navigate?</h3>
          <menu role="tablist">
            <button aria-selected="true" aria-controls="music">
              Music
            </button>
            <button aria-controls="dogs">Dogs</button>
            <button aria-controls="food">Food</button>
          </menu>
          <article role="tabpanel" id="music">
            <p>Set your listening preferences</p>
            <fieldset>
              <legend>Today's mood</legend>
              <div className="field-row">
                <input id="radio29" type="radio" name="fieldset-example2" />
                <label htmlFor="radio29">Nicki Minaj</label>
              </div>
              <div className="field-row">
                <input id="radio30" type="radio" name="fieldset-example2" />
                <label htmlFor="radio30">Bell Towers</label>
              </div>
              <div className="field-row">
                <input id="radio31" type="radio" name="fieldset-example2" />
                <label htmlFor="radio31">The Glamorous Monique</label>
              </div>
              <div className="field-row">
                <input id="radio32" type="radio" name="fieldset-example2" />
                <label htmlFor="radio32">EN. V</label>
              </div>
            </fieldset>
            <section className="field-row">
              <button>Reset Alarm...</button>
              <label>Try this to get some attention</label>
            </section>
          </article>

          <article role="tabpanel" hidden id="dogs">
            <p>OK</p>
          </article>

          <article role="tabpanel" hidden id="food">
            <p>
              You create the content for each tab by using an{" "}
              <code>article</code> tag.
            </p>
          </article>
        </WinForm>
        <StartBar />
      </main>
    </>
  );
}
